### ISSUE TITLE
debug vs Debug

### ISSUE THREAD

**Issue by ShamanTcler** [kenfred/conan-qwt#6]
So I am back to pester you again ... I will be posting multiple issues but keeping them separate for tracking

Simple one first: 

line 90
qwt_build_string = "CONFIG += %s" % ("release" if self.settings.build_type=="Release" else "debug")

I think it should be:
qwt_build_string = "CONFIG += %s" % ("release" if self.settings.build_type=="Release" else "Debug")

If you pass 
conan install . -s build_type=debug
ERROR: Invalid setting 'debug' is not a valid 'settings.build_type' value.
Possible values are ['Debug', 'MinSizeRel', 'None', 'RelWithDebInfo', 'Release']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"

So that is the easy one.

**Comment by kenfred** [comment]
No, `debug` corresponds to `release`, which is assigned to `CONFIG`, used in the Qt build system.
